/* Generated by Frama-C */
#include "stddef.h"
#include "stdio.h"
int level3_slice_1(int x)
{
  int __retres;
  __retres = x + 1;
  return __retres;
}

int level2_slice_1(int x)
{
  int __retres;
  int temp = level3_slice_1(x);
  __retres = temp * 2;
  return __retres;
}

int level1_slice_1(int x)
{
  int __retres;
  int result = level2_slice_1(x);
  __retres = result + 3;
  return __retres;
}

int main(void)
{
  int result;
  result = level1_slice_1(10);
  return result;
}


