/* Generated by Frama-C */
#include "stddef.h"
#include "stdio.h"
struct Point {
   int x ;
   int y ;
};
int divide(int dividend, int divisor)
{
  int __retres;
  /*@ assert rte: division_by_zero: divisor ≢ 0; */
  /*@ assert rte: signed_overflow: dividend / divisor ≤ 2147483647; */
  __retres = dividend / divisor;
  return __retres;
}

int modulo(int dividend, int divisor)
{
  int __retres;
  /*@ assert rte: division_by_zero: divisor ≢ 0; */
  /*@ assert rte: signed_overflow: dividend / divisor ≤ 2147483647; */
  __retres = dividend % divisor;
  return __retres;
}

int array_access(int *array, int index)
{
  int __retres;
  /*@ assert rte: pointer_alignment: \aligned(array + index,alignof(int)); */
  /*@ assert rte: mem_access: \valid_read(array + index); */
  __retres = *(array + index);
  return __retres;
}

void pointer_deref(int *ptr)
{
  /*@ assert rte: mem_access: \valid(ptr); */
  *ptr = 42;
  return;
}

int add_integers(int a, int b)
{
  int __retres;
  /*@ assert rte: signed_overflow: -2147483648 ≤ a + b; */
  /*@ assert rte: signed_overflow: a + b ≤ 2147483647; */
  __retres = a + b;
  return __retres;
}

int multiply_integers(int a, int b)
{
  int __retres;
  /*@ assert rte: signed_overflow: -2147483648 ≤ a * b; */
  /*@ assert rte: signed_overflow: a * b ≤ 2147483647; */
  __retres = a * b;
  return __retres;
}

int subtract_integers(int a, int b)
{
  int __retres;
  /*@ assert rte: signed_overflow: -2147483648 ≤ a - b; */
  /*@ assert rte: signed_overflow: a - b ≤ 2147483647; */
  __retres = a - b;
  return __retres;
}

int left_shift(int value, int shift_amount)
{
  int __retres;
  /*@ assert rte: shift: 0 ≤ shift_amount < 32; */
  /*@ assert rte: shift: 0 ≤ value; */
  /*@ assert rte: signed_overflow: value << shift_amount ≤ 2147483647; */
  __retres = value << shift_amount;
  return __retres;
}

int right_shift(int value, int shift_amount)
{
  int __retres;
  /*@ assert rte: shift: 0 ≤ shift_amount < 32; */
  __retres = value >> shift_amount;
  return __retres;
}

void fill_array(int *array, int size, int value)
{
  int i = 0;
  while (i < size) {
    /*@ assert rte: pointer_alignment: \aligned(array + i,alignof(int)); */
    /*@ assert rte: mem_access: \valid(array + i); */
    *(array + i) = value;
    /*@ assert rte: signed_overflow: i + 1 ≤ 2147483647; */
    i ++;
  }
  return;
}

int pointer_arithmetic(int *base, int offset)
{
  int __retres;
  int *ptr = base + offset;
  /*@ assert rte: mem_access: \valid_read(ptr); */
  __retres = *ptr;
  return __retres;
}

int matrix_access(int (*matrix)[10], int row, int col)
{
  int __retres;
  /*@ assert
        rte: pointer_alignment: \aligned(matrix + row,alignof(int [10]));
  */
  /*@ assert rte: index_bound: 0 ≤ col; */
  /*@ assert rte: index_bound: col < 10; */
  /*@ assert rte: mem_access: \valid_read(&(*(matrix + row))[col]); */
  __retres = (*(matrix + row))[col];
  return __retres;
}

void set_point(struct Point *p, int x, int y)
{
  /*@ assert rte: mem_access: \valid(&p->x); */
  p->x = x;
  /*@ assert rte: mem_access: \valid(&p->y); */
  p->y = y;
  return;
}

int nested_deref(int **ptr)
{
  int __retres;
  /*@ assert rte: pointer_alignment: \aligned(*ptr,alignof(int)); */
  /*@ assert rte: mem_access: \valid_read(ptr); */
  /*@ assert rte: mem_access: \valid_read(*ptr); */
  __retres = *(*ptr);
  return __retres;
}

int complex_expression(int a, int b, int c, int d)
{
  int __retres;
  /*@ assert rte: signed_overflow: -2147483648 ≤ a * b; */
  /*@ assert rte: signed_overflow: a * b ≤ 2147483647; */
  /*@ assert rte: signed_overflow: -2147483648 ≤ (int)(a * b) + c; */
  /*@ assert rte: signed_overflow: (int)(a * b) + c ≤ 2147483647; */
  /*@ assert rte: division_by_zero: d ≢ 0; */
  /*@ assert rte: signed_overflow: (int)((int)(a * b) + c) / d ≤ 2147483647;
  */
  __retres = (a * b + c) / d;
  return __retres;
}

void array_copy(int *dest, int const *src, int count)
{
  int i = 0;
  while (i < count) {
    /*@ assert rte: pointer_alignment: \aligned(dest + i,alignof(int)); */
    /*@ assert rte: mem_access: \valid(dest + i); */
    /*@ assert rte: pointer_alignment: \aligned(src + i,alignof(int const));
    */
    /*@ assert rte: mem_access: \valid_read(src + i); */
    *(dest + i) = *(src + i);
    /*@ assert rte: signed_overflow: i + 1 ≤ 2147483647; */
    i ++;
  }
  return;
}

int conditional_divide(int a, int b, int use_divide)
{
  int __retres;
  if (use_divide) {
    /*@ assert rte: division_by_zero: b ≢ 0; */
    /*@ assert rte: signed_overflow: a / b ≤ 2147483647; */
    __retres = a / b;
    goto return_label;
  }
  __retres = a;
  return_label: return __retres;
}

int string_length(char const *str)
{
  int len = 0;
  while (1) {
    /*@ assert
          rte: pointer_alignment: \aligned(str + len,alignof(char const));
    */
    /*@ assert rte: mem_access: \valid_read(str + len); */
    if (! ((int)*(str + len) != '\000')) break;
    /*@ assert rte: signed_overflow: len + 1 ≤ 2147483647; */
    len ++;
  }
  return len;
}

void increment_operations(int *value)
{
  /*@ assert rte: mem_access: \valid(value); */
  /*@ assert rte: mem_access: \valid_read(value); */
  /*@ assert rte: signed_overflow: *value + 1 ≤ 2147483647; */
  (*value) ++;
  /*@ assert rte: mem_access: \valid(value); */
  /*@ assert rte: mem_access: \valid_read(value); */
  /*@ assert rte: signed_overflow: -2147483648 ≤ *value - 1; */
  (*value) --;
  /*@ assert rte: mem_access: \valid(value); */
  /*@ assert rte: mem_access: \valid_read(value); */
  /*@ assert rte: signed_overflow: *value + 5 ≤ 2147483647; */
  *value += 5;
  /*@ assert rte: mem_access: \valid(value); */
  /*@ assert rte: mem_access: \valid_read(value); */
  /*@ assert rte: signed_overflow: -2147483648 ≤ *value - 3; */
  *value -= 3;
  return;
}

int switch_array_access(int *array, int selector)
{
  int __retres;
  switch (selector) {
    case 0: ;
    /*@ assert rte: pointer_alignment: \aligned(array + 0,alignof(int)); */
    /*@ assert rte: mem_access: \valid_read(array + 0); */
    __retres = *(array + 0);
    goto return_label;
    case 1: ;
    /*@ assert rte: pointer_alignment: \aligned(array + 1,alignof(int)); */
    /*@ assert rte: mem_access: \valid_read(array + 1); */
    __retres = *(array + 1);
    goto return_label;
    case 2: ;
    /*@ assert rte: pointer_alignment: \aligned(array + 2,alignof(int)); */
    /*@ assert rte: mem_access: \valid_read(array + 2); */
    __retres = *(array + 2);
    goto return_label;
    default: ;
    /*@ assert
          rte: pointer_alignment: \aligned(array + selector,alignof(int));
    */
    /*@ assert rte: mem_access: \valid_read(array + selector); */
    __retres = *(array + selector);
    goto return_label;
  }
  return_label: return __retres;
}

int multiple_errors(int *array, int size, int index, int divisor)
{
  int __retres;
  /*@ assert rte: pointer_alignment: \aligned(array + index,alignof(int)); */
  /*@ assert rte: mem_access: \valid_read(array + index); */
  int value = *(array + index);
  /*@ assert rte: signed_overflow: -2147483648 ≤ value * 2; */
  /*@ assert rte: signed_overflow: value * 2 ≤ 2147483647; */
  int doubled = value * 2;
  /*@ assert rte: division_by_zero: divisor ≢ 0; */
  /*@ assert rte: signed_overflow: doubled / divisor ≤ 2147483647; */
  int result = doubled / divisor;
  /*@ assert rte: pointer_alignment: \aligned(array + index,alignof(int)); */
  /*@ assert rte: mem_access: \valid(array + index); */
  *(array + index) = result;
  /*@ assert rte: signed_overflow: -2147483648 ≤ result + index; */
  /*@ assert rte: signed_overflow: result + index ≤ 2147483647; */
  __retres = result + index;
  return __retres;
}

unsigned int bitwise_ops(unsigned int value, int shift)
{
  unsigned int __retres;
  /*@ assert rte: shift: 0 ≤ shift < 32; */
  unsigned int shifted = value << shift;
  __retres = shifted >> 1;
  return __retres;
}

int ternary_divide(int a, int b, int c)
{
  int tmp;
  if (a > 0) 
    /*@ assert rte: division_by_zero: a ≢ 0; */
    /*@ assert rte: signed_overflow: b / a ≤ 2147483647; */
    tmp = b / a;
  else 
    /*@ assert rte: division_by_zero: a ≢ 0; */
    /*@ assert rte: signed_overflow: c / a ≤ 2147483647; */
    tmp = c / a;
  return tmp;
}

/*@ requires valid_read_string(format);
    assigns \result, __fc_stdout->__fc_FILE_data;
    assigns \result
      \from (indirect: __fc_stdout->__fc_FILE_id),
            (indirect: __fc_stdout->__fc_FILE_data),
            (indirect: *(format + (0 ..)));
    assigns __fc_stdout->__fc_FILE_data
      \from (indirect: __fc_stdout->__fc_FILE_id),
            __fc_stdout->__fc_FILE_data, (indirect: *(format + (0 ..)));
 */
int printf_va_1(char const * restrict format);

/*@ requires valid_read_string(format);
    assigns \result, __fc_stdout->__fc_FILE_data;
    assigns \result
      \from (indirect: __fc_stdout->__fc_FILE_id),
            (indirect: __fc_stdout->__fc_FILE_data),
            (indirect: *(format + (0 ..)));
    assigns __fc_stdout->__fc_FILE_data
      \from (indirect: __fc_stdout->__fc_FILE_id),
            __fc_stdout->__fc_FILE_data, (indirect: *(format + (0 ..)));
 */
int printf_va_2(char const * restrict format);

/*@ requires valid_read_string(format);
    assigns \result, __fc_stdout->__fc_FILE_data;
    assigns \result
      \from (indirect: __fc_stdout->__fc_FILE_id),
            (indirect: __fc_stdout->__fc_FILE_data),
            (indirect: *(format + (0 ..))), (indirect: param2),
            (indirect: param1), (indirect: param0);
    assigns __fc_stdout->__fc_FILE_data
      \from (indirect: __fc_stdout->__fc_FILE_id),
            __fc_stdout->__fc_FILE_data, (indirect: *(format + (0 ..))),
            param2, param1, param0;
 */
int printf_va_3(char const * restrict format, int param0, int param1,
                int param2);

/*@ requires valid_read_string(format);
    assigns \result, __fc_stdout->__fc_FILE_data;
    assigns \result
      \from (indirect: __fc_stdout->__fc_FILE_id),
            (indirect: __fc_stdout->__fc_FILE_data),
            (indirect: *(format + (0 ..)));
    assigns __fc_stdout->__fc_FILE_data
      \from (indirect: __fc_stdout->__fc_FILE_id),
            __fc_stdout->__fc_FILE_data, (indirect: *(format + (0 ..)));
 */
int printf_va_4(char const * restrict format);

/*@ requires valid_read_string(format);
    assigns \result, __fc_stdout->__fc_FILE_data;
    assigns \result
      \from (indirect: __fc_stdout->__fc_FILE_id),
            (indirect: __fc_stdout->__fc_FILE_data),
            (indirect: *(format + (0 ..))), (indirect: param0);
    assigns __fc_stdout->__fc_FILE_data
      \from (indirect: __fc_stdout->__fc_FILE_id),
            __fc_stdout->__fc_FILE_data, (indirect: *(format + (0 ..))),
            param0;
 */
int printf_va_5(char const * restrict format, int param0);

/*@ requires valid_read_string(format);
    assigns \result, __fc_stdout->__fc_FILE_data;
    assigns \result
      \from (indirect: __fc_stdout->__fc_FILE_id),
            (indirect: __fc_stdout->__fc_FILE_data),
            (indirect: *(format + (0 ..)));
    assigns __fc_stdout->__fc_FILE_data
      \from (indirect: __fc_stdout->__fc_FILE_id),
            __fc_stdout->__fc_FILE_data, (indirect: *(format + (0 ..)));
 */
int printf_va_6(char const * restrict format);

/*@ requires valid_read_string(format);
    assigns \result, __fc_stdout->__fc_FILE_data;
    assigns \result
      \from (indirect: __fc_stdout->__fc_FILE_id),
            (indirect: __fc_stdout->__fc_FILE_data),
            (indirect: *(format + (0 ..))), (indirect: param0);
    assigns __fc_stdout->__fc_FILE_data
      \from (indirect: __fc_stdout->__fc_FILE_id),
            __fc_stdout->__fc_FILE_data, (indirect: *(format + (0 ..))),
            param0;
 */
int printf_va_7(char const * restrict format, int param0);

/*@ requires valid_read_string(format);
    assigns \result, __fc_stdout->__fc_FILE_data;
    assigns \result
      \from (indirect: __fc_stdout->__fc_FILE_id),
            (indirect: __fc_stdout->__fc_FILE_data),
            (indirect: *(format + (0 ..)));
    assigns __fc_stdout->__fc_FILE_data
      \from (indirect: __fc_stdout->__fc_FILE_id),
            __fc_stdout->__fc_FILE_data, (indirect: *(format + (0 ..)));
 */
int printf_va_8(char const * restrict format);

/*@ requires valid_read_string(format);
    assigns \result, __fc_stdout->__fc_FILE_data;
    assigns \result
      \from (indirect: __fc_stdout->__fc_FILE_id),
            (indirect: __fc_stdout->__fc_FILE_data),
            (indirect: *(format + (0 ..))), (indirect: param0);
    assigns __fc_stdout->__fc_FILE_data
      \from (indirect: __fc_stdout->__fc_FILE_id),
            __fc_stdout->__fc_FILE_data, (indirect: *(format + (0 ..))),
            param0;
 */
int printf_va_9(char const * restrict format, int param0);

/*@ requires valid_read_string(format);
    assigns \result, __fc_stdout->__fc_FILE_data;
    assigns \result
      \from (indirect: __fc_stdout->__fc_FILE_id),
            (indirect: __fc_stdout->__fc_FILE_data),
            (indirect: *(format + (0 ..)));
    assigns __fc_stdout->__fc_FILE_data
      \from (indirect: __fc_stdout->__fc_FILE_id),
            __fc_stdout->__fc_FILE_data, (indirect: *(format + (0 ..)));
 */
int printf_va_10(char const * restrict format);

/*@ requires valid_read_string(format);
    assigns \result, __fc_stdout->__fc_FILE_data;
    assigns \result
      \from (indirect: __fc_stdout->__fc_FILE_id),
            (indirect: __fc_stdout->__fc_FILE_data),
            (indirect: *(format + (0 ..)));
    assigns __fc_stdout->__fc_FILE_data
      \from (indirect: __fc_stdout->__fc_FILE_id),
            __fc_stdout->__fc_FILE_data, (indirect: *(format + (0 ..)));
 */
int printf_va_11(char const * restrict format);

/*@ requires valid_read_string(format);
    assigns \result, __fc_stdout->__fc_FILE_data;
    assigns \result
      \from (indirect: __fc_stdout->__fc_FILE_id),
            (indirect: __fc_stdout->__fc_FILE_data),
            (indirect: *(format + (0 ..)));
    assigns __fc_stdout->__fc_FILE_data
      \from (indirect: __fc_stdout->__fc_FILE_id),
            __fc_stdout->__fc_FILE_data, (indirect: *(format + (0 ..)));
 */
int printf_va_12(char const * restrict format);

/*@ requires valid_read_string(format);
    assigns \result, __fc_stdout->__fc_FILE_data;
    assigns \result
      \from (indirect: __fc_stdout->__fc_FILE_id),
            (indirect: __fc_stdout->__fc_FILE_data),
            (indirect: *(format + (0 ..))), (indirect: param0);
    assigns __fc_stdout->__fc_FILE_data
      \from (indirect: __fc_stdout->__fc_FILE_id),
            __fc_stdout->__fc_FILE_data, (indirect: *(format + (0 ..))),
            param0;
 */
int printf_va_13(char const * restrict format, int param0);

/*@ requires valid_read_string(format);
    assigns \result, __fc_stdout->__fc_FILE_data;
    assigns \result
      \from (indirect: __fc_stdout->__fc_FILE_id),
            (indirect: __fc_stdout->__fc_FILE_data),
            (indirect: *(format + (0 ..)));
    assigns __fc_stdout->__fc_FILE_data
      \from (indirect: __fc_stdout->__fc_FILE_id),
            __fc_stdout->__fc_FILE_data, (indirect: *(format + (0 ..)));
 */
int printf_va_14(char const * restrict format);

/*@ requires valid_read_string(format);
    assigns \result, __fc_stdout->__fc_FILE_data;
    assigns \result
      \from (indirect: __fc_stdout->__fc_FILE_id),
            (indirect: __fc_stdout->__fc_FILE_data),
            (indirect: *(format + (0 ..)));
    assigns __fc_stdout->__fc_FILE_data
      \from (indirect: __fc_stdout->__fc_FILE_id),
            __fc_stdout->__fc_FILE_data, (indirect: *(format + (0 ..)));
 */
int printf_va_15(char const * restrict format);

/*@ requires valid_read_string(format);
    assigns \result, __fc_stdout->__fc_FILE_data;
    assigns \result
      \from (indirect: __fc_stdout->__fc_FILE_id),
            (indirect: __fc_stdout->__fc_FILE_data),
            (indirect: *(format + (0 ..)));
    assigns __fc_stdout->__fc_FILE_data
      \from (indirect: __fc_stdout->__fc_FILE_id),
            __fc_stdout->__fc_FILE_data, (indirect: *(format + (0 ..)));
 */
int printf_va_16(char const * restrict format);

/*@ requires valid_read_string(format);
    assigns \result, __fc_stdout->__fc_FILE_data;
    assigns \result
      \from (indirect: __fc_stdout->__fc_FILE_id),
            (indirect: __fc_stdout->__fc_FILE_data),
            (indirect: *(format + (0 ..)));
    assigns __fc_stdout->__fc_FILE_data
      \from (indirect: __fc_stdout->__fc_FILE_id),
            __fc_stdout->__fc_FILE_data, (indirect: *(format + (0 ..)));
 */
int printf_va_17(char const * restrict format);

/*@ requires valid_read_string(format);
    assigns \result, __fc_stdout->__fc_FILE_data;
    assigns \result
      \from (indirect: __fc_stdout->__fc_FILE_id),
            (indirect: __fc_stdout->__fc_FILE_data),
            (indirect: *(format + (0 ..)));
    assigns __fc_stdout->__fc_FILE_data
      \from (indirect: __fc_stdout->__fc_FILE_id),
            __fc_stdout->__fc_FILE_data, (indirect: *(format + (0 ..)));
 */
int printf_va_18(char const * restrict format);

/*@ requires valid_read_string(format);
    assigns \result, __fc_stdout->__fc_FILE_data;
    assigns \result
      \from (indirect: __fc_stdout->__fc_FILE_id),
            (indirect: __fc_stdout->__fc_FILE_data),
            (indirect: *(format + (0 ..)));
    assigns __fc_stdout->__fc_FILE_data
      \from (indirect: __fc_stdout->__fc_FILE_id),
            __fc_stdout->__fc_FILE_data, (indirect: *(format + (0 ..)));
 */
int printf_va_19(char const * restrict format);

/*@ requires valid_read_string(format);
    assigns \result, __fc_stdout->__fc_FILE_data;
    assigns \result
      \from (indirect: __fc_stdout->__fc_FILE_id),
            (indirect: __fc_stdout->__fc_FILE_data),
            (indirect: *(format + (0 ..)));
    assigns __fc_stdout->__fc_FILE_data
      \from (indirect: __fc_stdout->__fc_FILE_id),
            __fc_stdout->__fc_FILE_data, (indirect: *(format + (0 ..)));
 */
int printf_va_20(char const * restrict format);

int main(void)
{
  int __retres;
  int result;
  int array[10] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
  int value = 100;
  printf("=== RTE Example Program ===\n\n"); /* printf_va_1 */
  printf("1. Division: "); /* printf_va_2 */
  result = divide(100,5);
  printf("%d / %d = %d\n",100,5,result); /* printf_va_3 */
  printf("\n2. Array access: "); /* printf_va_4 */
  result = array_access(array,5);
  printf("array[5] = %d\n",result); /* printf_va_5 */
  printf("\n3. Pointer operations: "); /* printf_va_6 */
  pointer_deref(& value);
  printf("value = %d\n",value); /* printf_va_7 */
  printf("\n4. Integer arithmetic: "); /* printf_va_8 */
  result = add_integers(10,20);
  printf("10 + 20 = %d\n",result); /* printf_va_9 */
  printf("\n5. Array filling: "); /* printf_va_10 */
  fill_array(array,10,42);
  printf("Array filled with 42\n"); /* printf_va_11 */
  printf("\n6. Complex expression: "); /* printf_va_12 */
  result = complex_expression(2,3,4,5);
  printf("(2 * 3 + 4) / 5 = %d\n",result); /* printf_va_13 */
  printf("\n=== RTE Analysis Complete ===\n"); /* printf_va_14 */
  printf("\nTo see RTE annotations:\n"); /* printf_va_15 */
  printf("  frama-c -rte -print example.c\n\n"); /* printf_va_16 */
  printf("To verify with EVA:\n"); /* printf_va_17 */
  printf("  frama-c -rte -then -eva example.c\n\n"); /* printf_va_18 */
  printf("To prove with WP:\n"); /* printf_va_19 */
  printf("  frama-c -rte -then -wp example.c\n"); /* printf_va_20 */
  __retres = 0;
  return __retres;
}


